remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Recipe Analysis]
description: [An analysis on dataset recipes to test if there's a correlation the duration food cooked and rating]
gem "github-pages", group: :jekyll_plugins
